### ISSUE TITLE
Would this adapter work? 

### ISSUE THREAD

**Issue by TippyLion28** [Hypfer/esp8266-midea-dehumidifier#12]
Hi, I'm looking at picking up this kit instead of the level shifter+USB terminal adapter. Would this serve the same function? Thanks.

https://www.amazon.co.uk/gp/aw/d/B096K7VV1Y/

P. S. I'm about to purchase the Inventor EVA ION PRO WIFI so hopefully I'll be able to report back as to how well it works :)

**Comment by Hypfer** [comment]
Nope. Please re-read the readme.

Your adapter provides actual USB (as in the protocol) connectivity but that's not what is used by the dehumidifier.
You will need to buy what is documented in the readme.
