### ISSUE TITLE
Confirmed working Inventor EVA II Pro Wifi

### ISSUE THREAD

**Issue by juanbaldovi** [Hypfer/esp8266-midea-dehumidifier#2]
https://www.amazon.es/gp/product/B07XHMNSGJ

Big thanks!
Great work.

**Comment by bodiroga** [comment]
Hi @juanbaldovi!

Perhaps I'm a little bit offtopic here, but what Inventor model did you try? The EVA II Pro WiFi or the EVA ION Pro WiFi?

The last one is the only one that I see know in stock: [Amazon spain link](https://www.amazon.es/Deshumidificador-Inventor-EVA-WiFi-litros/dp/B08TC9ZWTY/ref=sr_1_1_sspa?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=eva+ii+pro+wifi&qid=1631113691&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExT1EzNEgxNUZXVkpIJmVuY3J5cHRlZElkPUEwMjMxODMyMTg1QUlXNkYzMUJRRiZlbmNyeXB0ZWRBZElkPUEwOTg2MzMzMzNaMFg0S0dQN0k1WCZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=).

Does anybody know if the EVA ION Pro WiFi model works fine with the esp8266? Any help?

Thank you for your help and best regard,

Aitor

**Comment by juanbaldovi** [comment]
Hello
I have tested EVA II Pro WiFi.
The link on Amazon is the same for EVA II Pro WiFi and EVA ION Pro WiFi so
I guess they updated the model.
On the photo, both look the same.
Regards

**Comment by bodiroga** [comment]
Hi again Juan!
 
Yeah, I have seen that both models look exactly the same and the manufacturer has already told me that they use the same WiFi adapter, so, in theory, the new EVA ION Pro WiFi should also work. Can I make you one more question? Was it very difficult to place the ESP8266 inside the dehumifier? Did you need to remove many screws and lose the product warranty? I'm a little bit worried about buying a new device to hack it from the beginning, but if it is not too complicated, I will try it and make a PR to this repo with my findings.

Mil gracias por tu ayuda (many thanks for your help) and best regards,

Aitor

**Comment by juanbaldovi** [comment]
Hello
the process is very simple, just remove a few screws, remove the original
adaptor from the USB and plug the one you build.
No soldering, etc
Regards

**Comment by bodiroga** [comment]
Excellent, thank you very much for your help! 👍🏻 

¡Un saludo!
