### ISSUE TITLE
Midea Cube 35

### ISSUE THREAD

**Issue by reijitamashii** [Hypfer/esp8266-midea-dehumidifier#29]
I set this up with a D1 mini clone and installed it in my Midea Cube 35 last week and everything is working well so far.  EDIT: It is reporting Humidity level and Wifi strength, and I can change the fan speed, humidity setpoint, mode, and power on/off.

The USB dongle is again in the same location as the 20 and 50 pint models.  Thank you!

**Comment by Hypfer** [comment]
Thanks!

**Comment by th0mcat** [comment]
@reijitamashii Where is the USB plug physically in the unit?
