### ISSUE TITLE
Reversibility

### ISSUE THREAD

**Issue by b3z** [Hypfer/esp8266-midea-dehumidifier#5]
Is this modification fully reversible? So can you easily switch back to the old setup?

**Comment by Hypfer** [comment]
I'd suggest reading the readme.md

**Comment by b3z** [comment]
I already followed your suggestion earlier.  And I also know that it is just swapping out a USB connected part. Still I wonder if there is some mechanism by the manufacturer that prevents swapping back. 
I understand that it would be logical for it to work. But still I’d like to know if anyone tried since the dehumidifier I am going to modify is not mine.

**Comment by Hypfer** [comment]
It should go without saying that one should only ever modify devices that they own.
